version: "3.5"

x-common:
  &x-common
  env_file:
    - ".env"

  logging:
    options:
      max-file: "5"
      max-size: 10m

  networks:
    - "navi2"
    - "shared"

  tty: true
  stdin_open: true

services:
  navi2:
    <<: *x-common
    image: navi2_dev
    build:
      context: .
    depends_on:
      - psql
    ports:
      - ${HTTP_PORT:-127.0.0.1:80}:80
    environment:
      POSTGRES_HOST: psql
      POSTGRES_PORT: 5432

  psql:
    <<: *x-common
    image: postgres:latest
    ports:
      - 127.0.0.1:5432:5432

networks:
  navi2:
  shared:
    name: shared
